{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "log-agent.fullname" . }}
  labels:
    {{- include "log-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - deletecollection
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - deletecollection
      - create
  - apiGroups:
      - extensions
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - deletecollection
      - create
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - deletecollection
      - create
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - deletecollection
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - deployments/finalizers
      - daemonsets/finalizers
      - replicasets/finalizers
      - statefulsets/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
      - leases/status
      - leases/status/conditions
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
      - deletecollection

{{- end }}