apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |-
    electorConfig:
      leaseLockName: {{ include "log-agent.leaseName" .}}
      leaseLockNamespace: {{ include "log-agent.leaseNamespace" .}}

metadata:
  name: {{ include "log-agent.fullname" . }}
  labels:
    {{- include "log-agent.labels" . | nindent 4}}
