apiVersion: v1
stringData:
  endpoint: {{ .Release.Name }}-master.{{ .Release.Namespace }}.svc
  port: "9200"
  username: "elastic"
  password: "{{ .Values.elasticPassword }}"
kind: Secret
metadata:
  name: {{ .Release.Name }}-credential
  namespace: {{ .Release.Namespace }}
type: Opaque